./scripts/vpg_train_exp2_fibercup.sh
./scripts/a2c_train_exp2_fibercup.sh
./scripts/acktr_train_exp2_fibercup.sh
./scripts/trpo_train_exp2_fibercup.sh
./scripts/ppo_train_exp2_fibercup.sh
./scripts/ddpg_train_exp2_fibercup.sh
./scripts/td3_train_exp2_fibercup.sh
./scripts/sac_train_exp2_fibercup.sh
./scripts/sac_auto_train_exp2_fibercup.sh
